version: '3.5'

services:
  prometheus:
    image: prom/prometheus
    user: root
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./tools/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock

  grafana:
    image: grafana/grafana
    user: root
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./.docker/grafana:/var/lib/grafana
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    user: root
    ports:
    - 8081:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - withprom=true
    depends_on:
    - postgres
    - app

  app:
    build: 
      context: .
      dockerfile: ./build/Dockerfile.dev
    environment:
      DEFAULT_DATABASE_URL: "postgres://root:root@postgres:5432/linkapi?sslmode=disable"
    restart: unless-stopped
    depends_on:
      - postgres
    labels:
      - withprom=true
    ports:
    - 8080:8080
    volumes:
    - ./:/app

  postgres:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
      POSTGRES_DB: linkapi
    volumes:
      - ./.docker/postgres:/data/postgres
    ports:
      - "5432:5432"

  postgres_exporter:
    image: "quay.io/prometheuscommunity/postgres-exporter"
    environment:
      DATA_SOURCE_NAME: "postgres://root:root@postgres:5432/postgres?sslmode=disable"
    ports:
      - "9187:9187"
    labels:
      - withprom=true
    
  k6:
    image: grafana/k6:latest
    command: ["run", "/scripts/shorten_link.js"]
    user: $DOCKER_USER
    profiles:
      - "loadtest"
    depends_on:
      - app
    volumes:
      - ./tools/k6:/scripts